version: "3.3"

services:
  accounts:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: accountecommerce

    ports:
      - 8091:8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    links:
      - postgres:postgres
    env_file:
      - ./env/django.env
    environment:
      - LOG_PATH=/var/log/applog/myapp.log
    volumes:
      - /opt/log:/var/log/applog

  postgres:
    image: postgres:10.4
    container_name: postgreseccommerce
    env_file:
      - ./env/postgresql.env
    volumes:
      - /opt/data:/var/lib/postgresql/data/
    links:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    hostname: rabbithostmq
    container_name: rabbithostmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/rabbithostmq:/etc/rabbithostmq/rabbithostmq.config