# Generated by Django 3.0.4 on 2020-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200323_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
