# Generated by Django 3.0.4 on 2020-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalCost',
            field=models.IntegerField(null=True),
        ),
    ]
